version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vkback
    restart: unless-stopped
    ports:
      - "5050:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app_network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: myapp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  redis_data:
  postgres_data:

networks:
  app_network:
    driver: bridge